import { createStyles } from '@mantine/core';

import { colors } from '../../constants/colors';

export const useStyles = createStyles((theme) => ({
  root: {
    display: 'flex',
    minHeight: '100vh',
  },

  // ── Left Branding Panel ──
  brandPanel: {
    flex: '0 0 45%',
    background: `linear-gradient(160deg, ${colors.primaryColor} 0%, #0D0D0D 100%)`,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    padding: '60px 48px',
    position: 'relative' as const,
    overflow: 'hidden',
    // Large decorative ring
    '&::before': {
      content: '""',
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
      width: 500,
      height: 500,
      borderRadius: '50%',
      border: `1px solid rgba(206,160,40,0.08)`,
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
      width: 350,
      height: 350,
      borderRadius: '50%',
      border: `1px solid rgba(206,160,40,0.05)`,
    },
    [theme.fn.smallerThan('md')]: {
      display: 'none',
    },
  },
  brandContent: {
    position: 'relative' as const,
    zIndex: 1,
    textAlign: 'center' as const,
    maxWidth: 340,
  },
  brandLogoWrapper: {
    width: 150,
    height: 150,
    borderRadius: 30,
    background: 'rgba(255,255,255,0.05)',
    border: '1px solid rgba(255,255,255,0.08)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 28px',
  },
  brandTitle: {
    fontSize: 34,
    fontWeight: 800,
    color: theme.white,
    lineHeight: 1.2,
    marginBottom: 12,
    letterSpacing: -0.5,
    [theme.fn.smallerThan('lg')]: { fontSize: 28 },
  },
  brandGold: {
    background: `linear-gradient(135deg, ${colors.secondaryColor}, ${colors.goldGradientEnd})`,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
  },
  brandTagline: {
    fontSize: 14,
    fontWeight: 600,
    color: colors.secondaryColor,
    letterSpacing: 3,
    textTransform: 'uppercase' as const,
    marginBottom: 24,
  },
  brandSubtext: {
    fontSize: 14,
    color: theme.colors.gray[6],
    lineHeight: 1.7,
  },
  brandDivider: {
    width: 40,
    height: 2,
    background: `linear-gradient(90deg, transparent, ${colors.secondaryColor}, transparent)`,
    margin: '32px auto',
    borderRadius: 2,
  },
  brandFeatures: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 20,
    marginTop: 8,
  },
  brandFeature: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    color: theme.colors.gray[5],
    fontSize: 14,
    textAlign: 'left' as const,
  },
  brandFeatureIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    background: `linear-gradient(135deg, rgba(206,160,40,0.15), rgba(206,160,40,0.05))`,
    border: '1px solid rgba(206,160,40,0.12)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  brandFooter: {
    position: 'absolute' as const,
    bottom: 32,
    left: 0,
    right: 0,
    textAlign: 'center' as const,
    zIndex: 1,
  },
  brandFooterText: {
    fontSize: 12,
    color: theme.colors.gray[7],
  },

  // ── Right Form Panel ──
  formPanel: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    padding: '40px 48px 60px',
    background: theme.colorScheme === 'light'
      ? `linear-gradient(180deg, ${theme.white} 0%, ${theme.colors.gray[0]} 100%)`
      : theme.colors.dark[7],
    overflowY: 'auto' as const,
    position: 'relative' as const,
    [theme.fn.smallerThan('md')]: {
      padding: '24px 20px 40px',
    },
  },
  formTopBar: {
    width: '100%',
    maxWidth: 440,
    display: 'flex',
    justifyContent: 'flex-start',
    marginBottom: 32,
    [theme.fn.smallerThan('md')]: {
      marginBottom: 24,
    },
  },
  backLink: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 13,
    fontWeight: 600,
    color: theme.colors.gray[6],
    textDecoration: 'none',
    transition: 'color 0.2s ease',
    '&:hover': {
      color: colors.secondaryColor,
      textDecoration: 'none',
    },
  },
  formWrapper: {
    width: '100%',
    maxWidth: 440,
  },
  formTitle: {
    fontSize: 30,
    fontWeight: 800,
    color: theme.colorScheme === 'light' ? colors.primaryColor : theme.white,
    marginBottom: 6,
    lineHeight: 1.2,
  },
  formSubtitle: {
    fontSize: 15,
    color: theme.colors.gray[6],
    marginBottom: 32,
    lineHeight: 1.5,
  },
  goldText: {
    color: colors.secondaryColor,
  },
  input: {
    '& input': {
      borderRadius: 10,
      height: 44,
      border: `1px solid ${theme.colorScheme === 'light' ? theme.colors.gray[3] : theme.colors.dark[4]}`,
      backgroundColor: theme.colorScheme === 'light' ? theme.white : theme.colors.dark[6],
      transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
      '&:focus, &:focus-within': {
        borderColor: colors.secondaryColor,
        boxShadow: '0 0 0 2px rgba(206,160,40,0.1)',
      },
    },
    '& .mantine-PasswordInput-innerInput': {
      height: 44,
    },
    '& .mantine-PasswordInput-input': {
      borderRadius: 10,
      height: 44,
      border: `1px solid ${theme.colorScheme === 'light' ? theme.colors.gray[3] : theme.colors.dark[4]}`,
      backgroundColor: theme.colorScheme === 'light' ? theme.white : theme.colors.dark[6],
      transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
      '&:focus-within': {
        borderColor: colors.secondaryColor,
        boxShadow: '0 0 0 2px rgba(206,160,40,0.1)',
      },
    },
    '& label': {
      fontWeight: 600,
      fontSize: 14,
      marginBottom: 6,
      color: theme.colorScheme === 'light' ? colors.primaryColor : theme.white,
    },
  },
  button: {
    backgroundColor: colors.secondaryColor,
    borderRadius: 30,
    height: 48,
    fontSize: 15,
    fontWeight: 600,
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 15px rgba(206,160,40,0.25)',
    '&:hover': {
      backgroundColor: colors.secondaryColorDark,
      transform: 'translateY(-2px)',
      boxShadow: '0 6px 20px rgba(206,160,40,0.35)',
    },
  },
  link: {
    fontSize: 13,
    color: theme.colors.gray[6],
    transition: 'color 0.2s ease',
    '&:hover': {
      color: colors.secondaryColor,
    },
  },
  iconBox: {
    width: 56,
    height: 56,
    borderRadius: 16,
    background: `linear-gradient(135deg, ${colors.secondaryColor}, ${colors.goldGradientEnd})`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 20px',
  },
}));
